server:
  port: 10010 # 网关端口
springdoc:
  swagger-ui:
    use-root-path: true
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: user-service # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://userservice # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/school/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        #          filters:
        #            - AddRequestHeader=sign, xn2001.com is eternal # 添加请求头
#        - id: course-service
#          uri: lb://courseservice
#          predicates:
#            - Path=/school/course/**
      #            - After=2031-04-13T15:14:47.433+08:00[Asia/Shanghai]
#      default-filters:
#        - AddRequestHeader=sign, xn2001.com is eternal # 添加请求头
#      globalcors: # 全局的跨域处理
#        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: # 允许哪些网站的跨域请求 allowedOrigins: “*” 允许所有网站
#              - "http://localhost:8090"
#            allowedMethods: # 允许的跨域ajax的请求方式
#              - "GET"
#              - "POST"
#              - "DELETE"
#              - "PUT"
#              - "OPTIONS"
#            allowedHeaders: "*" # 允许在请求中携带的头信息
#            allowCredentials: true # 是否允许携带cookie
#            maxAge: 360000 # 这次跨域检测的有效期
